bl_og/config/routes.rb
Rails.application.routes.draw do
  resources :screen_scrapings
  resources :cars
  get 'article/index'
  
  resources :articles do
    resources :comments
  end

  root 'cars#index'
end

bl_og/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

bl_og/app/models/article.rb
class Article < ApplicationRecord
  has_many :comments, dependent: :destroy
  validates :title, presence: true, length: { minimum: 5 }

  has_one_attached :image
end

bl_og/app/models/car.rb
class Car < ApplicationRecord
end

bl_og/app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
end

bl_og/app/models/screen_scraping.rb
class ScreenScraping < ApplicationRecord
end

bl_og/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

bl_og/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  
  http_basic_authenticate_with name: "denis281542", password: "Dd281542", except: [:index, :show]

  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def edit
    @article = Article.find(params[:id])
  end

  def create
    @article = Article.new(article_params)
 
    if @article.save
      redirect_to @article
    else
      render 'new'
    end
  end

  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to @article
    else
      render 'edit'
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    redirect_to articles_path
  end
 
  private
    def article_params
      params.require(:article).permit(:title, :text, :image)
    end
end

bl_og/app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_action :set_car, only: [:show, :edit, :update, :destroy]

  # GET /cars
  # GET /cars.json
  def index
    @cars = Car.all
  end

  # GET /cars/1
  # GET /cars/1.json
  def show
  end

  # GET /cars/new
  def new
    @car = Car.new
  end

  # GET /cars/1/edit
  def edit
  end

  # POST /cars
  # POST /cars.json
  def create
    @car = Car.new(car_params)

    respond_to do |format|
      if @car.save
        format.html { redirect_to @car, notice: 'Car was successfully created.' }
        format.json { render :show, status: :created, location: @car }
      else
        format.html { render :new }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cars/1
  # PATCH/PUT /cars/1.json
  def update
    respond_to do |format|
      if @car.update(car_params)
        format.html { redirect_to @car, notice: 'Car was successfully updated.' }
        format.json { render :show, status: :ok, location: @car }
      else
        format.html { render :edit }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cars/1
  # DELETE /cars/1.json
  def destroy
    @car.destroy
    respond_to do |format|
      format.html { redirect_to cars_url, notice: 'Car was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_car
      @car = Car.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def car_params
      params.require(:car).permit(:brand, :year_of_manufacture, :description)
    end
end

bl_og/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  
  http_basic_authenticate_with name: "denis281542", password: "Dd281542", only: :destroy

  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(comment_params)
    redirect_to article_path(@article)    
  end

  def destroy
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    @comment.destroy
    redirect_to article_path(@article)
  end

  private
  def comment_params
    params.require(:comment).permit(:commenter, :body)
  end
end

bl_og/app/controllers/screen_scrapings_controller.rb
class ScreenScrapingsController < ApplicationController
  before_action :set_screen_scraping, only: [:show, :edit, :update, :destroy]

  # GET /screen_scrapings
  # GET /screen_scrapings.json
  def index
    @screen_scrapings = ScreenScraping.all
  end

  # GET /screen_scrapings/1
  # GET /screen_scrapings/1.json
  def show
  end

  # GET /screen_scrapings/new
  def new
    @screen_scraping = ScreenScraping.new
  end

  # GET /screen_scrapings/1/edit
  def edit
  end

  # POST /screen_scrapings
  # POST /screen_scrapings.json
  def create
    @screen_scraping = ScreenScraping.new(screen_scraping_params)

    respond_to do |format|
      if @screen_scraping.save
        format.html { redirect_to @screen_scraping, notice: 'Screen scraping was successfully created.' }
        format.json { render :show, status: :created, location: @screen_scraping }
      else
        format.html { render :new }
        format.json { render json: @screen_scraping.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /screen_scrapings/1
  # PATCH/PUT /screen_scrapings/1.json
  def update
    respond_to do |format|
      if @screen_scraping.update(screen_scraping_params)
        format.html { redirect_to @screen_scraping, notice: 'Screen scraping was successfully updated.' }
        format.json { render :show, status: :ok, location: @screen_scraping }
      else
        format.html { render :edit }
        format.json { render json: @screen_scraping.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /screen_scrapings/1
  # DELETE /screen_scrapings/1.json
  def destroy
    @screen_scraping.destroy
    respond_to do |format|
      format.html { redirect_to screen_scrapings_url, notice: 'Screen scraping was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_screen_scraping
      @screen_scraping = ScreenScraping.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def screen_scraping_params
      params.fetch(:screen_scraping, {})
    end
end

bl_og/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

bl_og/app/helpers/application_helper.rb
module ApplicationHelper
end

bl_og/app/helpers/articles_helper.rb
module ArticlesHelper
end

bl_og/app/helpers/cars_helper.rb
module CarsHelper
end

bl_og/app/helpers/comments_helper.rb
module CommentsHelper
end

bl_og/app/helpers/screen_scrapings_helper.rb
module ScreenScrapingsHelper
end

bl_og/app/helpers/welcome_helper.rb
module WelcomeHelper
end

bl_og/app/views/cars/_form.html.erb
<%= form_with(model: car, local: true) do |form| %>
  <% if car.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(car.errors.count, "error") %> prohibited this car from being saved:</h2>

      <ul>
        <% car.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :brand %>
    <%= form.text_field :brand %>
  </div>

  <div class="field">
    <%= form.label :year_of_manufacture %>
    <%= form.number_field :year_of_manufacture %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

bl_og/app/views/cars/edit.html.erb
<h1>Editing Car</h1>

<%= render 'form', car: @car %>

<%= link_to 'Show', @car %> |
<%= link_to 'Back', cars_path %>

bl_og/app/views/cars/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Cars</h1>

<table>
  <thead>
    <tr>
      <th>Brand</th>
      <th>Year of manufacture</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cars.each do |car| %>
      <tr>
        <td><%= car.brand %></td>
        <td><%= car.year_of_manufacture %></td>
        <td><%= car.description %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Car', new_car_path %>
<br>
<%= link_to 'Scaping', new_screen_scraping_path %>

bl_og/app/views/cars/new.html.erb
<h1>New Car</h1>

<%= render 'form', car: @car %>

<%= link_to 'Back', cars_path %>

bl_og/app/views/cars/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Brand:</strong>
  <%= @car.brand %>
</p>

<p>
  <strong>Year of manufacture:</strong>
  <%= @car.year_of_manufacture %>
</p>

<p>
  <strong>Description:</strong>
  <%= @car.description %>
</p>

<%= link_to 'Edit', edit_car_path(@car) %> |
<%= link_to 'Back', cars_path %>

bl_og/app/views/comments/_comment.html.erb
<p>
  <strong>Commenter:</strong>
  <%= comment.commenter %>
</p>
 
<p>
  <strong>Comment:</strong>
  <%= comment.body %>
</p>

<p>
 <%= link_to 'Destroy Comment', [comment.article, comment], method: :delete, data: { confirm: 'Are you sure?' } %>  
</p>

bl_og/app/views/comments/_form.html.erb
<%= form_with(model: [ @article, @article.comments.build ], local: true) do |form| %>
  <p>
    <%= form.label :commenter %><br>
    <%= form.text_field :commenter %>
  </p>
  <p>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

bl_og/app/views/comments/calendar.html.erb
<h1>123</h1>

bl_og/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  </head>

  <body>
    <%= yield %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

bl_og/app/views/screen_scrapings/_form.html.erb
<%= form_with(model: screen_scraping, local: true) do |form| %>
  <% if screen_scraping.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(screen_scraping.errors.count, "error") %> prohibited this screen_scraping from being saved:</h2>

      <ul>
        <% screen_scraping.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

bl_og/app/views/screen_scrapings/edit.html.erb
<h1>Editing Screen Scraping</h1>

<%= render 'form', screen_scraping: @screen_scraping %>

<%= link_to 'Show', @screen_scraping %> |
<%= link_to 'Back', screen_scrapings_path %>

bl_og/app/views/screen_scrapings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Screen Scrapings</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @screen_scrapings.each do |screen_scraping| %>
      <tr>
        <td><%= link_to 'Show', screen_scraping %></td>
        <td><%= link_to 'Edit', edit_screen_scraping_path(screen_scraping) %></td>
        <td><%= link_to 'Destroy', screen_scraping, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Screen Scraping', new_screen_scraping_path %>

bl_og/app/views/screen_scrapings/new.html.erb
<h1>New Screen Scraping</h1>

<%= render 'form', screen_scraping: @screen_scraping %>

<%= link_to 'Back', screen_scrapings_path %>

bl_og/app/views/screen_scrapings/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_screen_scraping_path(@screen_scraping) %> |
<%= link_to 'Back', screen_scrapings_path %>